syntax = "proto3"; // Версия синтаксиса Protobuf

package romance_club; // Пространство имён

import "episode.proto"; // Подключаю episode.proto

// Запрос на получение эпизода по ID
message GetEpisodeRequest {
  int32 id = 1; // ID эпизода
}

// Запрос на получение всех эпизодов
message GetAllEpisodesRequest {
  // Пустой запрос
}

// Ответ со всеми эпизодами
message GetAllEpisodesResponse {
  repeated Episode episodes = 1; // Список эпизодов
}

// Запрос на сохранение эпизода
message SaveEpisodeRequest {
  Episode episode = 1; // Эпизод
}

// Ответ после сохранения
message SaveEpisodeResponse {
  bool success = 1; // Успешно ли сохранение
  string message = 2; // Сообщение
}

// gRPC-сервис для работы с эпизодами
service EpisodeApi {
  rpc GetEpisode(GetEpisodeRequest) returns (Episode); // Получить эпизод по ID
  rpc GetAllEpisodes(GetAllEpisodesRequest) returns (GetAllEpisodesResponse); // Получить все эпизоды
  rpc SaveEpisode(SaveEpisodeRequest) returns (SaveEpisodeResponse); // Сохранить эпизод
}